# Generated by Django 5.1.5 on 2025-01-27 15:50

from django.db import migrations


def add_initial_tags(apps, schema_editor):
    Tag = apps.get_model('blog', 'Tag')
    tags = [
        'Technology', 'Science', 'Health', 'Politics', 'Business', 'Art', 'Travel', 'Food', 'Sports', 'Education',
        'Environment', 'Space', 'History', 'Culture', 'Music', 'Movies', 'Books', 'Gaming', 'Fashion', 'Design',
        'Photography', 'Philosophy', 'Psychology', 'Sociology', 'Economics', 'Finance', 'Marketing', 'Engineering',
        'Agriculture', 'Energy', 'Climate Change', 'Artificial Intelligence', 'Machine Learning', 'Data Science', 'Cybersecurity'
    ]
    for tag_name in tags:
        Tag.objects.create(name=tag_name)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag_post_tags'),
    ]

    operations = [
        migrations.RunPython(add_initial_tags),
    ]
